/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizzator;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.Timer;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dam102
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    int cuantos = 0;
    Cola Pedidos = new Cola();
    Pila Compleados = new Pila();
    Timer Temporizador;
    int Pedidos_Actuales;

    Color greenPizzaHut = new Color(1, 169, 143);

    Border greenBorder = BorderFactory.createLineBorder(greenPizzaHut, 2);
    Border blackBorder = BorderFactory.createLineBorder(Color.gray, 1);
    Border noSelected = BorderFactory.createRaisedBevelBorder();

    Border empty = BorderFactory.createEmptyBorder();
    Border title = BorderFactory.createTitledBorder(
            blackBorder, "Ingredientes Extras");

    Border raisedbevel = BorderFactory.createRaisedBevelBorder();
    Border loweredbevel = BorderFactory.createLoweredBevelBorder();
    Border compound = BorderFactory.createCompoundBorder(
            raisedbevel, loweredbevel);

    Boolean IconChampiIsSelected = false;
    Boolean IconPepinillosIsSelected = false;
    Boolean IconAceitunasIsSelected = false;
    Boolean IconQuesoIsSelected = false;

    public Ventana() throws ClassNotFoundException {

        initComponents();

        jPanel_Ingredientes.setBorder(title);
        jScrollPane2.setBorder(blackBorder);
        TFieldDatos.setBorder(compound);
//        CB_Tamanio.setBorder(blackBorder);
//        CB_TipoBase.setBorder(blackBorder);

        Temporizador = new Timer(50, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                PBarTiempo.setValue(PBarTiempo.getValue() + 1);

                if (PBarTiempo.getValue() == PBarTiempo.getMaximum()) {
                    Pizza Piz;
                    PBarTiempo.setValue(0);
                    Piz = Pedidos.Primero();
                    Pedidos.Quitar();
                    TFieldDatos.setText(Piz.toString());
                    Compleados.Insertar(Piz);

                    DefaultTableModel Temp = (DefaultTableModel) TablaPedidos.getModel();
                    Temp.removeRow(0);
                    TablaPedidos.setModel(Temp);

                    Pedidos_Actuales--;

                    if (Pedidos.Esta_Vacia()) {
                        Temporizador.stop();
                    }
                }

            }
        });

        CB_Tamanio.addItem("TAMAÑOS");
        CB_Tamanio.addItem("Familiar");
        CB_Tamanio.addItem("Mediana");
        CB_Tamanio.addItem("Pequeña");

        CB_TipoBase.addItem("BASES");
        CB_TipoBase.addItem("Finissima");
        CB_TipoBase.addItem("Calzzone");
        CB_TipoBase.addItem("Borde Queso");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Ingredientes = new javax.swing.JPanel();
        IconChampi = new javax.swing.JLabel();
        IconQueso = new javax.swing.JLabel();
        IconAceitunas = new javax.swing.JLabel();
        IconPepinillos = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        BT_Pedido = new javax.swing.JButton();
        PBarTiempo = new javax.swing.JProgressBar();
        ImagenPizzaHut = new javax.swing.JLabel();
        TituloProgessBar = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaPedidos = new javax.swing.JTable();
        TFieldDatos = new javax.swing.JTextField();
        CB_Tamanio = new javax.swing.JComboBox<String>();
        CB_TipoBase = new javax.swing.JComboBox<String>();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("~ Pizzator ~");
        setMinimumSize(new java.awt.Dimension(1050, 850));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel_Ingredientes.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingredientes Extras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        jPanel_Ingredientes.setForeground(new java.awt.Color(255, 102, 102));
        jPanel_Ingredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel_Ingredientes.setMinimumSize(new java.awt.Dimension(150, 150));
        jPanel_Ingredientes.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEADING, 10, 10));

        IconChampi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconChampi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/champinones-dieta-adelgazar-xl-668x400x80xX.jpg"))); // NOI18N
        IconChampi.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IconChampi.setIconTextGap(10);
        IconChampi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconChampiMouseClicked(evt);
            }
        });
        jPanel_Ingredientes.add(IconChampi);

        IconQueso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconQueso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/queso-rayado.jpg"))); // NOI18N
        IconQueso.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IconQueso.setIconTextGap(10);
        IconQueso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconQuesoMouseClicked(evt);
            }
        });
        jPanel_Ingredientes.add(IconQueso);

        IconAceitunas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconAceitunas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/aceitunas-manzanilla-con-hueso.jpg"))); // NOI18N
        IconAceitunas.setToolTipText("");
        IconAceitunas.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        IconAceitunas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IconAceitunas.setIconTextGap(10);
        IconAceitunas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconAceitunasMouseClicked(evt);
            }
        });
        jPanel_Ingredientes.add(IconAceitunas);

        IconPepinillos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IconPepinillos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pepinillos-gigantes.jpg"))); // NOI18N
        IconPepinillos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        IconPepinillos.setIconTextGap(10);
        IconPepinillos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IconPepinillosMouseClicked(evt);
            }
        });
        jPanel_Ingredientes.add(IconPepinillos);

        getContentPane().add(jPanel_Ingredientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 230, 245));

        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 50));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, 20, 580));

        BT_Pedido.setBackground(new java.awt.Color(1, 169, 143));
        BT_Pedido.setText("Aceptar Pedido");
        BT_Pedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_PedidoActionPerformed(evt);
            }
        });
        getContentPane().add(BT_Pedido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 660, 140, 40));

        PBarTiempo.setForeground(new java.awt.Color(1, 169, 143));
        getContentPane().add(PBarTiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 680, 290, 20));

        ImagenPizzaHut.setBackground(new java.awt.Color(1, 169, 143));
        ImagenPizzaHut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pizza-Hut-Icon.png"))); // NOI18N
        getContentPane().add(ImagenPizzaHut, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 450, 130));

        TituloProgessBar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TituloProgessBar.setText("Tiempo para servir...");
        getContentPane().add(TituloProgessBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 650, 170, 20));

        TablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tamaño", "Tipo Base", "Ingred. Extra", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaPedidos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane2.setViewportView(TablaPedidos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 520, 180));

        TFieldDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFieldDatosActionPerformed(evt);
            }
        });
        getContentPane().add(TFieldDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 450, 520, 100));

        CB_Tamanio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CB_Tamanio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CB_Tamanio, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 530, 90, -1));

        CB_TipoBase.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        CB_TipoBase.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(CB_TipoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 90, -1));

        label1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label1.setText("Pedidos actuales");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 170, -1, -1));

        label2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label2.setText("Pedidos Servidos");
        getContentPane().add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void BT_PedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_PedidoActionPerformed

        int Cont = 0;
        int Cantidad = 0;
        Pizza Piz;
        float Precio = 0;
        float PrecioTotal = 0;
        String Tam = null, Tipo_Pizza = null;
        String Ingredientes[] = new String[5];

        if (CB_Tamanio.getSelectedIndex() != 0 && CB_TipoBase.getSelectedIndex() != 0) {

            switch (CB_Tamanio.getSelectedIndex()) {

                case 1:
                    Precio = 15;
                    Tam = "Familiar";
                    break;
                case 2:
                    Precio = 10;
                    Tam = "Mediana";
                    break;
                case 3:
                    Precio = 5;
                    Tam = "Pequeña";

            }

            switch (CB_TipoBase.getSelectedIndex()) {

                case 1:
                    Tipo_Pizza = "Finissima";

                    break;
                case 2:
                    Tipo_Pizza = "Calzzone";

                    break;
                case 3:
                    Tipo_Pizza = "Bordes Queso";

            }

            if (IconAceitunasIsSelected) {
                Ingredientes[Cont] = "Amarillo";
                Cont++;
            }
            if (IconChampiIsSelected) {
                Ingredientes[Cont] = "Rojo";
                Cont++;
            }
            if (IconPepinillosIsSelected) {
                Ingredientes[Cont] = "Verde";
                Precio++;
                Cont++;
            }

            if (IconQuesoIsSelected) {
                Ingredientes[Cont] = "Azul";
                Cont++;

            }

            PrecioTotal = Precio + (Cont * 4);

            do {
                Piz = new Pizza(Tam, Tipo_Pizza, Ingredientes, Precio);

                Pedidos.Insertar(Piz);

                if (TablaPedidos.getRowCount() == Pedidos_Actuales) {

                    DefaultTableModel Temp;
                    Temp = (DefaultTableModel) TablaPedidos.getModel();
                    Object Nueva_fila[] = new Object[3];
                    Nueva_fila[0] = "";
                    Nueva_fila[1] = 0;
                    Nueva_fila[2] = false;
                    Temp.addRow(Nueva_fila);
                    TablaPedidos.setModel(Temp);

                }

                TablaPedidos.setValueAt(Tam, Pedidos_Actuales, 0);
                TablaPedidos.setValueAt(Tipo_Pizza, Pedidos_Actuales, 1);
                TablaPedidos.setValueAt(Cont, Pedidos_Actuales, 2);
                TablaPedidos.setValueAt(PrecioTotal, Pedidos_Actuales, 3);
                Pedidos_Actuales++;

                Cantidad--;

            } while (Cantidad > 0);

            IconAceitunasIsSelected = false;
            IconChampiIsSelected = false;
            IconPepinillosIsSelected = false;
            IconQuesoIsSelected = false;

            IconAceitunas.setBorder(noSelected);
            IconChampi.setBorder(noSelected);
            IconPepinillos.setBorder(noSelected);
            IconQueso.setBorder(noSelected);

            CB_Tamanio.setSelectedIndex(0);
            CB_TipoBase.setSelectedIndex(0);

            Temporizador.start();
            javax.swing.JOptionPane.showMessageDialog(null, "Pedido confirmado", "Correcto", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } else {
            javax.swing.JOptionPane.showMessageDialog(null, "Por favor revise la seleccion de tamaño y base", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_BT_PedidoActionPerformed

    private void IconPepinillosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconPepinillosMouseClicked
        if (evt.getClickCount() % 2 == 0) {
            IconPepinillos.setBorder(greenBorder);
            IconPepinillosIsSelected = true;

        } else {
            IconPepinillos.setBorder(noSelected);
        }

    }//GEN-LAST:event_IconPepinillosMouseClicked

    private void IconQuesoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconQuesoMouseClicked
        if (evt.getClickCount() % 2 == 0) {
            IconQueso.setBorder(greenBorder);
            IconQuesoIsSelected = true;

        } else {
            IconQueso.setBorder(noSelected);
        }
    }//GEN-LAST:event_IconQuesoMouseClicked

    private void IconChampiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconChampiMouseClicked
        if (evt.getClickCount() % 2 == 0) {
            IconChampi.setBorder(greenBorder);
            IconChampiIsSelected = true;

        } else {
            IconChampi.setBorder(noSelected);
        }
    }//GEN-LAST:event_IconChampiMouseClicked

    private void IconAceitunasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconAceitunasMouseClicked
        if (evt.getClickCount() % 2 == 0) {
            IconAceitunas.setBorder(greenBorder);
            IconAceitunasIsSelected = true;

        } else {
            IconAceitunas.setBorder(noSelected);
        }
    }//GEN-LAST:event_IconAceitunasMouseClicked

    private void TFieldDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFieldDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFieldDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_Pedido;
    private javax.swing.JComboBox<String> CB_Tamanio;
    private javax.swing.JComboBox<String> CB_TipoBase;
    private javax.swing.JLabel IconAceitunas;
    private javax.swing.JLabel IconChampi;
    private javax.swing.JLabel IconPepinillos;
    private javax.swing.JLabel IconQueso;
    private javax.swing.JLabel ImagenPizzaHut;
    private javax.swing.JProgressBar PBarTiempo;
    private javax.swing.JTextField TFieldDatos;
    private javax.swing.JTable TablaPedidos;
    private javax.swing.JLabel TituloProgessBar;
    private javax.swing.JPanel jPanel_Ingredientes;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables
}
